#!/bin/bash
IMAGE=$DOCKER_USERNAME/latex2image

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

if [[ "$TRAVIS_BRANCH" != "master" ]]; then
  IMAGE=$DOCKER_USERNAME/latex2image-$TRAVIS_BRANCH
fi

docker push $IMAGE:${TRAVIS_COMMIT::8}
docker tag $IMAGE:${TRAVIS_COMMIT::8} $IMAGE:latest
docker push $IMAGE:latest
