# Generated by Django 3.2.10 on 2022-03-02 04:05

import re

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import latex.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex_key', models.TextField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Tex Key')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time')),
                ('image', models.ImageField(blank=True, null=True, storage=latex.models.OverwriteStorage(), upload_to='l2i_images')),
                ('data_url', models.TextField(blank=True, null=True, verbose_name='Data Url')),
                ('compile_error', models.TextField(blank=True, null=True, verbose_name='Compile Error')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'LaTeXImage',
                'verbose_name_plural': 'LaTeXImages',
            },
        ),
    ]
