# Generated by Django 3.2.10 on 2022-03-01 09:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lateximage',
            options={'verbose_name': 'LaTeXImage', 'verbose_name_plural': 'LaTeXImages'},
        ),
        migrations.AlterField(
            model_name='lateximage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lateximage',
            name='tex_key',
            field=models.TextField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Tex Key'),
        ),
    ]
